version: "3.7"
services:
  django-db:
    platform: linux/x86_64
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=mysitedb"
      - "MYSQL_USER=mysitedbuser"
      - "MYSQL_PASSWORD=mysitedbpassword"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:3.8.3-management"
    ports:
      - "5672:5672"
      - "15672:15672"